{% set name = "torch_sparse" %}
{% set version = "0.6.10" %}

package:
  name: py{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e2c7a3649d04e19b3b3960c1d7fc0e767017c93587de1e0d6eb7fda613a6b82

build:
  number: 1
  skip: true  # [win]
  script:
    - export FORCE_CUDA="1"    # [linux64 and cudatoolkit not in (undefined, 'None')]
    - export CC="$GCC"   # [linux64 and cudatoolkit not in (undefined, 'None')]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python {{ python }}
    - pytorch-base {{ pytorch }}
    - pip
    - setuptools {{ setuptools }}
    - pytest-runner
    - scipy {{ scipy }}
  run:
    - python {{ python }}
    - pytorch-base {{ pytorch }}
    - pytest
    - pytest-cov
    - scipy {{ scipy }}
    - pytorch_scatter {{ pytorch_scatter }}

test:
  imports:
    - torch_sparse

about:
  home: https://github.com/rusty1s/pytorch_sparse
  summary: PyTorch Extension Library of Optimized Autograd Sparse Matrix Operations
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/rusty1s/pytorch_sparse

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
