{% set name = "torch_sparse" %}
{% set version = "0.6.18" %}

package:
  name: py{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f14c510a6e93f404c6ea357210615b3c15a71731f9dbd86f25434e34fb5a741

build:
  number: 1
  string: {{ build_type }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }} #[build_type == 'cpu']
  string: {{ build_type }}{{ cudatoolkit | replace(".*", "") }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }} #[build_type == 'cuda']
  skip: true  # [win]
  script:
    - export FORCE_CUDA="1"    # [build_type == 'cuda']
    - export CC="$GCC"   # [build_type == 'cuda']
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cudatoolkit {{ cudatoolkit }}     # [build_type == 'cuda']
  host:
    - cudatoolkit {{ cudatoolkit }}     # [build_type == 'cuda']
    - python {{ python }}
    - _pytorch_select  {{ pytorch_select_version }}
    - pytorch-base {{ pytorch }}
    - pip
    - setuptools {{ setuptools }}
    - pytest-runner
    - scipy {{ scipy }}
  run:
    - python {{ python }}
    - cudatoolkit {{ cudatoolkit }}     # [build_type == 'cuda']
    - _pytorch_select  {{ pytorch_select_version }}
    - pytorch-base {{ pytorch }}
    - pytest
    - pytest-cov
    - scipy {{ scipy }}
    - pytorch_scatter {{ pytorch_scatter }}

test:
  imports:
    - torch_sparse

about:
  home: https://github.com/rusty1s/pytorch_sparse
  summary: PyTorch Extension Library of Optimized Autograd Sparse Matrix Operations
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/rusty1s/pytorch_sparse

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
